apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: whoami
  namespace: demo
  labels:
    app: whoami
spec:
  replicas: 3
  selector:
    matchLabels:
      app: whoami
  template:
    metadata:
      labels:
        app: whoami
    spec:
      containers:
        - name: whoami
          image: containous/whoami:v1.4.0
          ports:
            - containerPort: 80
          env:
            - name: TEST
              value: TESTING
          command:
            - /whoami
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 3
          resources:
            limits:
              cpu: "1"
              memory: 512Mi
            requests:
              memory: 256Mi
              cpu: "0.5"